# Generated by Django 4.2.6 on 2024-03-20 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_mcq_capturedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceAuth',
        ),
    ]
