# Generated by Django 4.2.6 on 2024-04-03 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0004_delete_faceauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('LongDescriptive', 'Long Descriptive Answer Question')], max_length=20)),
                ('question_text', models.TextField(max_length=500)),
                ('option1', models.TextField(blank=True, max_length=100, null=True)),
                ('option2', models.TextField(blank=True, max_length=100, null=True)),
                ('option3', models.TextField(blank=True, max_length=100, null=True)),
                ('option4', models.TextField(blank=True, max_length=100, null=True)),
                ('correct_option', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
    ]
