# Generated by Django 4.2.6 on 2024-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_question_useranswer_delete_mcq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
    ]
