# Generated by Django 4.2.6 on 2024-04-04 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_remove_useranswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='examination_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 4, 10, 24, 57, 517202)),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examresult'),
        ),
    ]
