"""
Django settings for proctoring project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging
import psutil

 


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMP_DIR = os.path.join(BASE_DIR, 'templates')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7q$%9al+meyfbv%02$1x45kdq32nz8($p3inie33isud32+8fj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'users',
    'image_ai',
    'exams',
    'screen_recorder',

    'django_cleanup.apps.CleanupConfig',
   
]

MIDDLEWARE = [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

 
]

# Allow all domains for simplicity during development
# CORS_ALLOWED_ORIGINS = ["*"]
   

ROOT_URLCONF = 'proctoring.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMP_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proctoring.wsgi.application'
ASGI_APPLICATION = "proctoring.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'proctoringdb2',  # Replace with your database name
#         'USER': 'root',  # Replace with your PostgreSQL username
#         'PASSWORD': 'root',  # Replace with your PostgreSQL password
#         'HOST': 'localhost',  # Set the hostname or IP address of your PostgreSQL server
#         # 'HOST': 'db',
#         # 'PORT': '5432',  # Set the PostgreSQL port
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'proctoringdb2',
        'USER': 'cis',
        'PASSWORD': 'cis',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'null': {
#             'class': 'logging.NullHandler',
#         },
#     },
#     'root': {
#         'handlers': ['null'],
#         'level': 'ERROR', 
#     },
# }


SECURE_BROWSER_XSS_FILTER = False
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = 'static/'

MEDIA_URL = '/media/'

# Path where media is stored
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": ["redis://redis:6379/0"],
        },
    },
}
MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"


available_memory = psutil.virtual_memory().available
fraction = 0.5 # Use 50% of available memory
# Set DATA_UPLOAD_MAX_MEMORY_SIZE to a larger value (e.g., 20MB).
# DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 20MB in bytes
# DATA_UPLOAD_MAX_MEMORY_SIZE = 1000 * 1024 * 1024 
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

DATA_UPLOAD_MAX_MEMORY_SIZE = int(available_memory*fraction)
MINIMUM_MEMORY_SIZE = 20 * 1024 * 1024  # 20MB
if DATA_UPLOAD_MAX_MEMORY_SIZE < MINIMUM_MEMORY_SIZE:
    DATA_UPLOAD_MAX_MEMORY_SIZE = MINIMUM_MEMORY_SIZE



JAZZMIN_SETTINGS = {
    "site_title" : "CIS Proctoring",
    "copyright" : "Cyber Infrastructure Pvt. Ltd",
    "welcome_sign": "Welcome to CIS Proctoring",
    "site_logo": "images/cis_logo.png",
    "site_header": "CIS",
    "site_brand": "CIS",
    "site_title" : "CIS"
}